/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PlayRoomIdRouteImport } from './routes/play/$roomId'
import { Route as ApiRoomsRoomIdRouteImport } from './routes/api/rooms/$roomId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoomIdRoute = PlayRoomIdRouteImport.update({
  id: '/play/$roomId',
  path: '/play/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomsRoomIdRoute = ApiRoomsRoomIdRouteImport.update({
  id: '/api/rooms/$roomId',
  path: '/api/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/play/$roomId': typeof PlayRoomIdRoute
  '/api/rooms/$roomId': typeof ApiRoomsRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/play/$roomId': typeof PlayRoomIdRoute
  '/api/rooms/$roomId': typeof ApiRoomsRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/play/$roomId': typeof PlayRoomIdRoute
  '/api/rooms/$roomId': typeof ApiRoomsRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/play/$roomId' | '/api/rooms/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/play/$roomId' | '/api/rooms/$roomId'
  id: '__root__' | '/' | '/about' | '/play/$roomId' | '/api/rooms/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PlayRoomIdRoute: typeof PlayRoomIdRoute
  ApiRoomsRoomIdRoute: typeof ApiRoomsRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$roomId': {
      id: '/play/$roomId'
      path: '/play/$roomId'
      fullPath: '/play/$roomId'
      preLoaderRoute: typeof PlayRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms/$roomId': {
      id: '/api/rooms/$roomId'
      path: '/api/rooms/$roomId'
      fullPath: '/api/rooms/$roomId'
      preLoaderRoute: typeof ApiRoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PlayRoomIdRoute: PlayRoomIdRoute,
  ApiRoomsRoomIdRoute: ApiRoomsRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
